spring.application.name=relacionamento

spring.datasource.url=jdbc:postgresql://localhost:5432/relacionamento
spring.datasource.username=postgres
spring.datasource.password=jogadornumero01

spring.jpa.hibernate.ddl-auto=update
