spring.application.name=relacionamento

#spring.datasource.url=jdbc:postgresql://localhost:5432/relacionamento
#spring.datasource.username=postgres
#spring.datasource.password=jogadornumero01

spring.datasource.url=jdbc:h2:mem:relacionamento
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
